package com.nexus.libs.error.model;

/**
 * Error Codes
 */
public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    INTERNAL_ERROR,
    SKU_REQUIRED,
    PRODUCT_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    ACCESS_DENIED,
    ADDRESS_NOT_FOUND,
    INVALID_OPERATION,
    TENANT_NOT_FOUND,
    INVALID_TENANT_TYPE,
    TENANT_MISMATCH,
    USER_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    ORDER_NOT_FOUND,
    CART_NOT_FOUND,
    PAYMENT_FAILED,
    INVENTORY_INSUFFICIENT,
    BAD_REQUEST,
    CATEGORY_NAME_ALREADY_EXISTS,
    INVALID_PARENT_CATEGORY,
    CATEGORY_HAS_PRODUCTS,
    CATEGORY_HAS_CHILDREN,
    INSUFFICIENT_STOCK,
    INVALID_REQUEST,
    BAD_CREDENTIALS,
    EMAIL_TAKEN,
    PHONE_TAKEN,
    LOCATION_NOT_FOUND,
    LOCATION_NAME_ALREADY_EXISTS,
    ADDRESS_DUPLICATE,
    PROFILE_NOT_FOUND
}

