import {
  LayoutDashboard,
  Stethoscope,
  Baby,
  Clock,
  BookOpen,
  Calendar,
  FileText,
  CreditCard,
  Award,
  GraduationCap,
  Heart,
  Users,
  Building,
  Camera,
  MapPin,
  Star,
  Pill,
  Phone,
  Shield,
  Settings,
} from 'lucide-react';

export const navItems = [
  {
    name: 'Dashboard',
    route: '/admin',
    icon: LayoutDashboard,
    subItems: null,
  },
  {
    name: 'Doctors',
    route: '/admin/doctors',
    icon: Stethoscope,
    subItems: [
      { name: 'All Doctors', route: '/admin/doctors', icon: Stethoscope },
      { name: 'Awards', route: '/admin/doctors/awards', icon: Award },
      { name: 'Qualifications', route: '/admin/doctors/qualifications', icon: GraduationCap },
      { name: 'Specializations', route: '/admin/doctors/specializations', icon: Heart },
      { name: 'Memberships', route: '/admin/doctors/memberships', icon: Users },
      { name: 'Organizations', route: '/admin/doctors/organizations', icon: Building },
      { name: 'Registrations', route: '/admin/doctors/registrations', icon: FileText },
      { name: 'Photos', route: '/admin/doctors/photos', icon: Camera },
      { name: 'Practices', route: '/admin/doctors/practices', icon: MapPin },
      { name: 'Recommendations', route: '/admin/doctors/recommendations', icon: Star },
    ],
  },
  {
    name: 'Patients',
    route: '/admin/patients',
    icon: Baby,
    subItems: [
      { name: 'All Patients', route: '/admin/patients', icon: Baby },
      { name: 'Allergies', route: '/admin/patients/allergies', icon: Heart },
      { name: 'Medications', route: '/admin/patients/medications', icon: Pill },
      { name: 'Emergency Contacts', route: '/admin/patients/emergency-contacts', icon: Phone },
      { name: 'Medical History', route: '/admin/patients/medical-history', icon: FileText },
      { name: 'Appointments', route: '/admin/patients/appointments', icon: Calendar },
      { name: 'Insurance', route: '/admin/patients/insurance', icon: Shield },
      { name: 'Addresses', route: '/admin/patients/addresses', icon: MapPin },
    ],
  },
  {
    name: 'Appointments',
    route: '/admin/appointments',
    icon: Calendar,
    subItems: null,
  },
  {
    name: 'Sessions',
    route: '/admin/sessions',
    icon: BookOpen,
    subItems: [
      { name: 'Session Types', route: '/admin/sessions/types', icon: Settings },
      { name: 'Session Offerings', route: '/admin/sessions/offerings', icon: BookOpen },
    ],
  },
  {
    name: 'Availability',
    route: '/admin/availability',
    icon: Clock,
    subItems: null,
  },
  {
    name: 'Time Offs',
    route: '/admin/time-offs',
    icon: Clock,
    subItems: null,
  },
  {
    name: 'Branches',
    route: '/admin/branches',
    icon: Building,
    subItems: null,
  },
  {
    name: 'Payments',
    route: '/admin/payments',
    icon: CreditCard,
    subItems: null,
  },
  {
    name: 'Reports',
    route: '/admin/reports',
    icon: FileText,
    subItems: null,
  },
];

